modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="sff"
version="1.0.0"
displayName="Simple Force Field"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="GunMetalBlack"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



